is:
#  - headers.acceptJson
#  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatCalcId
#  - errors.NinoNotFound
#  - errors.calcIdNotFount
#  - errors.invalidCredentials
#  - errors.clientOrAgentNotAuthorised
#  - errors.reportNotGenereated ####

displayName: Produce a Transactional Risking Calculation Report
description: This endpoint allows the developer to generate and return a report for the previous tax calculation and taxpayer.
#(annotations.sandboxData): !include ../../scenarios/selfAssessment/retrieveIncomeTaxAndNics.md
(annotations.scope): "read:hmrc-self-assessment-assist"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:hmrc-self-assessment-assist" ] } ]
responses:
  200:


# 200:
#   body:
#     application/json:
#       type: !include ../../schemas/selfAssessmec/retrieve_incomeTaxAndNics_response.json
#       examples:
#         example-1:
#            description: Example calculation response.
#            value: !include ../../examples/acknowledge/confirmReportProcessed.json
#   headers:
#      X-CorrelationId:
#        example: c75f40a6-a3df-4429-a697-471eeec46435
#        description: Unique ID for operation tracking <br> String, 36 characters.