is:
#  - headers.acceptJson
#  - headers.testScenarioHeader
  - errors.formatNino
  - errors.invalidCredentials
  - errors.clientOrAgentNotAuthorised
  - errors.reportNotFound

displayName: Acknowledge report
description: This endpoint allows you acknowledge that the report has received and read or processed in some way.
#(annotations.sandboxData): !include ../../scenarios/selfAssessment/retrieveIncomeTaxAndNics.md
(annotations.scope): "write:hmrc-self-assessment-assist"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:hmrc-self-assessment-assist" ] } ]
responses:
  204:
  500:
